spring:
  rabbitmq:
    listener:
      simple:
        auto-startup: false
  jpa:
    hibernate:
      ddl-auto: validate
enrichment:
  messaging:
    retry-delay-milliseconds: 100
  outbox:
    publisher-enabled: false
