spring:
  application:
    name: data-enrichment-service
  jackson:
    property-naming-strategy: SNAKE_CASE
    deserialization:
      fail-on-unknown-properties: true
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.xml

enrichment:
  event-time-zone: UTC
